[project]
name = "fast-eq-windows"
version = "0.2.0"
description = "A fast GUI for switching to the correct EverQuest window that you want to see."
readme = "README.md"
authors = [
    { name = "Andrew Cook", email = "awcook97@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dearpygui>=2.3",
]

[project.scripts]
fast-eq-windows = "fast_eq_windows:main"

[dependency-groups]
dev = [
    "pyinstaller>=6.0",
]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
